version: "3.9"
services:
  backend:
    build: ./backend
    container_name: locker-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - locker-net

  frontend:
    build: ./frontend
    container_name: locker-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - locker-net

networks:
  locker-net: